flood_adapt/integrator/sfincs_adapter.py
flood_adapt/object_model/hazard/hazard.py

The function to translate hurricanes was missing the argument site because it was not passed by the SfincsAdapter. Minor fix thus

translate hurricane function was missing site argument

---

flood_adapt/integrator/sfincs_adapter.py

pavbnd in the overland sfincs.inp file was not correctly changed when using offshore model boundary conditions

fixed pavbnd bug

---

flood_adapt/object_model/hazard/hazard.py

closes https://github.com/Deltares-research/FloodAdapt/issues/307 
This contains some fixes to also run offshore simulations in a probabilistic event set. And it reuses existing spiderweb files and will not create a new one every time a hurricane is run.
There is still an outstanding issue in the frontend to remove existing spiderweb files if a hurricane event is edited. But these backend changes are not dependent on the frontend issue and can already be reviewed and merged

307 add hurricanes to risk ensemble

---

flood_adapt/api/measures.py
flood_adapt/object_model/direct_impact/measure/buyout.py
flood_adapt/object_model/direct_impact/measure/elevate.py
flood_adapt/object_model/direct_impact/measure/floodproof.py
flood_adapt/object_model/hazard/measure/floodwall.py
flood_adapt/object_model/hazard/measure/green_infrastructure.py
flood_adapt/object_model/hazard/measure/pump.py
flood_adapt/object_model/interface/measures.py

Add the option of setting the database input path to a none. It doesn't change anything for FloodAdapt but for de modelbuider (where there is no database), it can now also be used to make models. And also add the thin dam and culvert options

Make measure creation more general

---

flood_adapt/object_model/hazard/hazard.py
tests/test_integrator/test_hazard_run.py
tests/test_object_model/test_scenarios.py

That was a very peculiar error where I had added n * SLR (with n being the number of synthetic or nearshore_historical events). In the probabilistic event set we have 60 nearshore_historical events so instead of adding 1ft of SLR FloodAdapt added 60ft. Hence the crazy floodmap Kathryn got.
This happened in the function hazard.add_wl(), which was actually only called once in hazard.preprocess_sfincs(). Both functions looped over all events in the event set and this is where I must have been adding SLR n times. I removed the function hazard.add_wl() since it just made it confusing and led to this error and moved its functionality directly into hazard.preprocess_sfincs(). The fix also includes an updated test to check whether SLR has been added correctly.

341 fix slr in event sets

---

flood_adapt/dbs_controller.py
flood_adapt/integrator/sfincs_adapter.py

There were issues with files that were staying after the SFincsAdapter was run.
- One issue was connected with the netcdf files staying open, which was resolved by using a garbage collector whenever the a SfincsAdapter is deleted.
- The second issue was with the log file handler for the SfincsAdapter which was sometimes using the last handle (which could even be a diffent SFINCS model). This was resolved by resetting the loggers file handler every time a new SfincsAdapter object is initialized.

File handles closing

---

flood_adapt/api/output.py
flood_adapt/dbs_controller.py
flood_adapt/integrator/fiat_adapter.py
flood_adapt/integrator/sfincs_adapter.py
flood_adapt/object_model/direct_impacts.py
flood_adapt/object_model/hazard/hazard.py
flood_adapt/object_model/interface/site.py
flood_adapt/object_model/scenario.py
tests/test_object_model/test_benefits.py

- Added a netcdf file with the max water levels in the Flooding folder of the results for each scenario to be used instead of the actual simulation
- Implemented the deletion of the simulation folders for SFINCS and FIAT if it is chosen in the site.toml
- Changed the has_run checks for both Hazard and Direct_Impacts to ensure only post-processed output is checked.

355 option to delete simulation folders for sfincs and fiat

---

flood_adapt/integrator/sfincs_adapter.py

and also converting possible  MultiLineStrings to LineStrings to work with hydromt-sfincs
At the moment, this requires the shape file to have a z-column. Otherwise, the uniform elevation value from the GUI will be taken. I am trying to make this neater in the GUI by allowing the user to specify whether a unifrom value should be used for all floodwalls or which column should eb taken from the shape file. But I have not succeeded yet. This will be a future PR in the GUI

using z-value in floodwall from shp file 

---

tests/test_integrator/test_fiat_adapter.py

issue resolved in HydroMT-FIAT (https://github.com/Deltares/hydromt_fiat/pull/302). Updated the unit-test in FloodAdapt with respect to this.

409 raise by datum is currently increasing the elevation above ground and not datum

---

flood_adapt/object_model/hazard/measure/green_infrastructure.py

This contains a small fix to calculate the area of all polygons. The current code assumed that the geojson contains only one polygon. But this is only the case when the polygon is drawn inside the user interface, not when it is imported from a shape file.

total area of all polygons from imported file

---

flood_adapt/api/events.py
flood_adapt/api/output.py
flood_adapt/dbs_classes/dbs_benefit.py
flood_adapt/dbs_classes/dbs_event.py
flood_adapt/dbs_classes/dbs_interface.py
flood_adapt/dbs_classes/dbs_measure.py
flood_adapt/dbs_classes/dbs_projection.py
flood_adapt/dbs_classes/dbs_scenario.py
flood_adapt/dbs_classes/dbs_strategy.py
flood_adapt/dbs_classes/dbs_template.py
flood_adapt/dbs_controller.py
flood_adapt/object_model/direct_impacts.py
flood_adapt/object_model/hazard/hazard.py
flood_adapt/object_model/scenario.py

These are all to get more consistent naming in the code (no more accidental capitals/non-capitals)
- Fix input, output, static and base path in the database
- Use these paths in the code
- Use the get function in Hazards and DirectImpacts
- Extend the database classes to automatically give the path to it's corresponding directory

Fix naming issues

---

flood_adapt/dbs_controller.py
flood_adapt/object_model/scenario.py

Don't copy the hazad if it is comming from itself
Also to make it visible that a scenario rerun is attempted, append to the logging instead of removing the entire file
This also needed to make sure all other loggers were closed

Add self check to hazard run check

---

flood_adapt/object_model/direct_impacts.py

added a check to see if the risk infographic config is available and if not to produce an error

 risk infographic config check

---

flood_adapt/__init__.py
flood_adapt/config.py
flood_adapt/dbs_controller.py
flood_adapt/object_model/hazard/hazard.py

quickfix for now, but a better, more permanent solution will be a part of the pydantic-settings PR (https://github.com/Deltares-research/FloodAdapt/pull/546) that is in review at the moment.

make deleting run output optional

---

flood_adapt/__init__.py
flood_adapt/config.py
flood_adapt/dbs_controller.py
flood_adapt/object_model/hazard/hazard.py

Usage:
from windows terminal:
```bash
set DELETE_CRASHED_RUNS=False
python floodadapt_run.py
```
from linux terminal:
```
export DELETE_CRASHED_RUNS=True
python floodadapt_run.py
```
from a python file
```python
from flood_adapt.config import Settings
Settings(
delete_crashed_runs=False
)
... # the rest of the script
```
Any time Settings() is called, 
1. It first reads the arguments it was given.
2. Then it fills unset fields with environment variables.
3. If there are still unset fields, it will use the defaults defined in the Settings class. 
4. Then it will run all validators, and update the environment with its current state.

Move delete crashed runs var to Settings class

---

cliff.toml

url of the repo in cliff.toml still had the ci-playground url where I developed this and I forgot to update it. This PR rectifies that.

fix(misc): fix repo url in cliff.toml

---

.commitlintrc.yml

a lot of the things we do in the post-processing are not necessarily connected with the models, and people using the backend might be interested in what changes in the outputs that flood adapt generates, so making a separate scope for this makes sense

feat(misc): add output as a conventional commit scope

---

flood_adapt/database_builder/create_database.py

Replace the $ default damage unit with the damage unit from the fiat model

feat(dbs-builder):replace $ with fiat model damage unit in metrics

---

flood_adapt/api/measures.py
flood_adapt/object_model/hazard/event/hurricane.py

module level code gets executed when importing the module. This includes fn arguments, class attr defaults etc.
Since Settings() instantiation can raise, it shouldnt be executed if not 100% required

fix(misc): remove Settings() instantiation from module level code

---

flood_adapt/adapter/sfincs_adapter.py

There was a part that was run in the post-processing step of the sfincs adapter that was creating single event output for each event in the event_set, with the same name, essentially overwriting in each iteration the files. This is now deleted.

fix(adapters): Take out part that was creating single event output

---

flood_adapt/object_model/hazard/forcing/plotting.py
flood_adapt/object_model/hazard/forcing/tide_gauge.py

Units were not correctly interpreted when plotting gauged water level data. There was no conversion done on the actual noaa time-series which are in meters, before plotting them in the html which should be in feet.

fix(object-model): Correcting units in gauge plotting

---

flood_adapt/adapter/sfincs_adapter.py
flood_adapt/adapter/sfincs_offshore.py
flood_adapt/database_builder/create_database.py
flood_adapt/dbs_classes/database.py
flood_adapt/misc/config.py
flood_adapt/object_model/hazard/event/historical.py
flood_adapt/object_model/hazard/event/hurricane.py
flood_adapt/object_model/hazard/event/synthetic.py
flood_adapt/object_model/hazard/forcing/discharge.py
flood_adapt/object_model/hazard/forcing/plotting.py
flood_adapt/object_model/hazard/forcing/rainfall.py
flood_adapt/object_model/hazard/forcing/tide_gauge.py
flood_adapt/object_model/hazard/forcing/timeseries.py
flood_adapt/object_model/hazard/forcing/waterlevels.py
flood_adapt/object_model/hazard/forcing/wind.py
flood_adapt/object_model/hazard/interface/models.py
flood_adapt/object_model/hazard/interface/timeseries.py
tests/conftest.py
tests/fixtures.py
tests/test_adapter/test_sfincs_adapter.py
tests/test_object_model/test_events/test_eventset.py
tests/test_object_model/test_events/test_forcing/test_discharge.py
tests/test_object_model/test_events/test_forcing/test_forcing_factory.py
tests/test_object_model/test_events/test_forcing/test_waterlevels.py
tests/test_object_model/test_events/test_hurricane.py
tests/test_object_model/test_events/test_tide_gauge.py
tests/test_object_model/test_events/test_timeseries.py
tests/test_object_model/test_scenarios.py

fixes #665 
https://github.com/Deltares-research/FloodAdapt-GUI/pull/488

fix(object-model): coarse timeseries for imported csv files

---

flood_adapt/adapter/sfincs_adapter.py

now all waterlevel forcings that are added to the model are updated with +msl and -localdatum
How it used to be implemented: 
https://github.com/Deltares-research/FloodAdapt/blob/3cef1953d14f2eba8cde624a05fe3bd369210b21/flood_adapt/object_model/hazard/hazard.py#L432C12-L437C14

fix(adapters): updated waterlevel references in Sfincs adapter 

---

flood_adapt/adapter/fiat_adapter.py
flood_adapt/database_builder/create_database.py
flood_adapt/object_model/interface/config/fiat.py
pixi.lock
pyproject.toml
tests/test_adapter/test_fiat_adapter.py
tests/test_api/test_static_data.py

With this update the latest changes in fiat_toolbox are used. Now a FiatColumns class defines the expected FIAT columns and their string formatting. This way, one formatting is tighted to the FIAT output based on the FIAT version used, and one is tighted to the FloodAdapt output which can be defined in the FiatAdapter.

refactor(adapters): Use pydantic model for defining impact columns formatting

---

pyproject.toml

use latest release of fiat_toolbox, which solved a number of bugs in the footprint aggregation method

dep(adapters): Update fiat_toolbox version to fix output bugs

---

flood_adapt/config/fiat.py
flood_adapt/database_builder/database_builder.py
tests/test_database_builder/test_database_builder.py
tests/test_flood_adapt.py

Sarah found bugs while writing notebooks. This fixes them.
The problem was that there was no event set, but fiat was expecting it.

fix(dbs-builder): make BenefitsModel and RiskModel in FiatModel optional

---

flood_adapt/dbs_classes/dbs_template.py

Fixes issue where you cannot edit an object.
There was a check for the name of the object already existing that was taking place all the time while it should not when overwrite is true
N/A

fix(dbs-controller): Corrected saving object validation issue which did not allow editing 

---

docs/examples/events/database_manipulation.ipynb
flood_adapt/dbs_classes/dbs_benefit.py
flood_adapt/dbs_classes/dbs_scenario.py
flood_adapt/dbs_classes/dbs_template.py
flood_adapt/dbs_classes/interface/element.py
flood_adapt/flood_adapt.py
tests/test_flood_adapt.py

The edit method was essentially a save with overwrite, which was now added as an option in the save method, in order to completely take out all the edit methods for each object.

refactor(dbs-controller): Take out edit methods from API and add overwrite option in save method

---

flood_adapt/config/site.py
flood_adapt/dbs_classes/database.py
flood_adapt/dbs_classes/dbs_event.py
flood_adapt/dbs_classes/dbs_projection.py
flood_adapt/dbs_classes/dbs_strategy.py
flood_adapt/dbs_classes/dbs_template.py
tests/data/create_test_static.py
tests/test_dbs_classes/test_database.py

Fixes #778 
Pass standard objects to the `__init__` of DbsTemplate and updated the function `_check_standard_objects` to use them.
Added `create_standard_objects` to the script `create_test_static.py`.

refactor(dbs-controller): Enhance standard object protection handling

---

flood_adapt/adapter/sfincs_adapter.py

Fixes [#575](https://github.com/Deltares-research/FloodAdapt-GUI/issues/575)

fix(output): always add the measured waterlevels in output markers except for synthetic events

---

flood_adapt/objects/events/historical.py
flood_adapt/objects/events/hurricane.py
tests/data/create_test_input.py
tests/test_flood_adapt.py
tests/test_objects/test_events/test_eventset.py
tests/test_objects/test_events/test_historical.py
tests/test_objects/test_events/test_offshore.py
tests/test_objects/test_forcing/test_waterlevels.py

Fixes #823
due to a bug in how hydromtsfincs handles METEO data, we cannot run the offshore modcel for historical events.

fix(object-model): temporarily disable METEO and MODEL forcings

---

flood_adapt/database_builder/database_builder.py
tests/test_database_builder/test_database_builder.py

The default references in the config is a having the "MSL" set to 0. But we need to always provide a reference for the overland SFINCS model. If this is not "MSL", the user needs to know that they have to add the datum in the references list. 
Now, the user only needs to provide a name for the reference of the SFINCS model. Then if the user does not provide manualy a water level reference obejct, the SFINCS ref name will be used as the main reference in the water level references object, and assumed=0. 
Then the standard updates if a NOAA station is used, will take place

refactor(dbs-builder): Update how dbs builder gets default water level references

---

flood_adapt/adapter/sfincs_adapter.py

fixed issue when tide gauge was not available and observation was plotted

fix(adapter): Tide gauge was assmumed to always be there during obs point html creation

---

flood_adapt/dbs_classes/dbs_static.py
flood_adapt/flood_adapt.py

During one of the last iterations, the models in the dbs_static class were cached. This created issues during initializations of the database class. 
This was done to speed up some calls in the gui. This was now acchieved by using the scenario.has_run method instead of the scenario.hazard_run_check method which is a lot slower.
If the scenario is run, by definition the hazard has been run.

fix(dbs-controller): Remove caching of models and check for scenario run instead of hazard run
