flood_adapt/api/strategies.py
flood_adapt/dbs_controller.py
flood_adapt/object_model/interface/database.py
flood_adapt/object_model/strategy.py
tests/test_api/test_strategy.py

Strategy API and DBcontroller

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/documentation_improvement.yaml

corrected the names in the issues forms

corrected names in issue forms

---

environment.yml
pyproject.toml

fixed pydantic version to 1.10.9 to avoid errors when installing with the latest pydantic release

fixed pydantic version

---

flood_adapt/dbs_controller.py

Calculation was right (including the SLR up until the reference year). But in the plot I did not subtract the SLR up until the reference year, hence the interpolated value and plot were inconsistent. I fixed the plot now to make it consistent. I had discussed this with Kathryn

186 wrong slr calculations

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/documentation_improvement.yaml
flood_adapt/dbs_controller.py
flood_adapt/object_model/interface/site.py

This fixes both the delete protection and the standard events. It is linked to GUI issue 78

129 add delete protection for events projections scenarios and strategies

---

.gitignore
flood_adapt/integrator/sfincs_adapter.py
flood_adapt/object_model/hazard/hazard.py
tests/test_integrator/test_hazard_run.py

adding floodmap creation for single scenario after every sfincs run

adding floodmap geotiff creation and test

---

flood_adapt/api/events.py
flood_adapt/dbs_controller.py
flood_adapt/integrator/sfincs_adapter.py
flood_adapt/object_model/hazard/event/event.py
flood_adapt/object_model/hazard/event/historical_nearshore.py
flood_adapt/object_model/hazard/event/synthetic.py
flood_adapt/object_model/hazard/hazard.py
flood_adapt/object_model/interface/database.py
flood_adapt/object_model/interface/site.py
tests/test_api/test_scenarios.py
tests/test_integrator/test_hazard_run.py
tests/test_object_model/test_benefits.py
tests/test_object_model/test_events.py
tests/test_object_model/test_scenarios.py

fixing unit conversion for timeseries

---

flood_adapt/integrator/fiat_adapter.py
flood_adapt/object_model/direct_impact/measure/impact_measure.py
flood_adapt/object_model/direct_impacts.py

Changes:
- Added timer for FIAT preprocessing and running
- Added the FiatModel as argument to the get_object_ids function to not read the model each time the object ids are retrieved

Small fixes fiat

---

flood_adapt/object_model/direct_impacts.py
flood_adapt/object_model/hazard/hazard.py
flood_adapt/object_model/scenario.py
tests/test_database.py

writing separate sfincs and fiat log files, hydromt is missing things up a bit

writing sfincs log files to separte log file in simulations folder

---

flood_adapt/integrator/fiat_adapter.py

reversed to the previous version that had fiat risk working

changed back to working risk version

---

flood_adapt/api/output.py
flood_adapt/object_model/direct_impacts.py
flood_adapt/object_model/scenario.py

Multiple fixes for infographics

---

flood_adapt/api/startup.py
flood_adapt/dbs_controller.py
flood_adapt/object_model/interface/site.py

needed for https://github.com/Deltares/FloodAdapt-GUI/issues/66

added svi data configuration and api

---

environment.yml
flood_adapt/dbs_controller.py
flood_adapt/integrator/fiat_adapter.py
flood_adapt/integrator/sfincs_adapter.py
flood_adapt/object_model/direct_impacts.py
flood_adapt/object_model/hazard/hazard.py
flood_adapt/object_model/scenario.py

Closes #242 
Just to clarify, I added the logger cleanup as a destructor to make sure that you only and always clean it up at the end of using the adapter. From what I could see, the single adapter instance is not used anymore after the positions I deleted them right? I did check it but that might be something to check carefully for the reviewer

242 allow deleting scenario if it has been run

---

flood_adapt/object_model/io/unitfulvalue.py

Also checkout to the same branch name for FloodAdapt-GUI repo and review changes.

93 plot ingredients of selected projection

---

flood_adapt/object_model/benefit.py
tests/test_database/charleston/static/site/site.toml
tests/test_database/charleston/static/site/site_without_river.toml
tests/test_object_model/test_benefits.py

In order to include the equity weighted benefits I needed to do quite some changes, so I decided to tackle issue #301 at the same time, by changing the method of the aggregation areas, and using generalized static methods to not repeat the same code.

benefits - include equity weighted benefit calculation

---

flood_adapt/api/output.py
flood_adapt/api/startup.py
flood_adapt/dbs_controller.py
flood_adapt/integrator/sfincs_adapter.py
flood_adapt/object_model/hazard/hazard.py
flood_adapt/object_model/interface/database.py
flood_adapt/object_model/interface/site.py
tests/test_database/charleston/static/site/site.toml
tests/test_integrator/test_hazard_run.py
tests/test_integrator/test_sfincs_adapter.py

Waiting for coordination with Maarten to finalize this

272 create time series hmtl for water levels at obervation stations

---

tests/test_integrator/test_sfincs_adapter.py

I noticed that it does not delete an existing sfincs.obs file when no ob points are provided in the site.toml
Maybe this is something to tackle later. I am not sure how to use HydroMT Sfincs for that.

fixing test

---

tests/test_database.py
tests/test_object_model/test_benefits.py

small correction for the unit tests to make sure the database files are consistent

corrected unit tests

---

flood_adapt/object_model/interface/measures.py

with the new pydantic version all Optional attributes should have a default value

added floodwall default value for absolute_elevation attribute

---

tests/conftest.py

Update optional revert of contents of versioned files Update optional cleanup of unversioned files
Update docstrings

Update automatic update the database to latest revision.

---

flood_adapt/object_model/interface/benefits.py
flood_adapt/object_model/interface/events.py
flood_adapt/object_model/interface/measures.py
flood_adapt/object_model/interface/projections.py
flood_adapt/object_model/interface/scenarios.py
flood_adapt/object_model/interface/strategies.py

Validator to exclude unwanted characters from the name. Apparently the //// is needed to actually exclude a backslash. This is because it is also used as the escape character

Add validators

---

flood_adapt/object_model/hazard/event/historical_hurricane.py

minor change (4 lines of code). The function was already included in the cht_cyclone toolbox. I just made an if statement to turn it on when rainfall from track is chosen.

include rainfall in spw file if rainfall from track is chosen

---

flood_adapt/dbs_controller.py

to be merged with https://github.com/Deltares-research/FloodAdapt-GUI/pull/414

Bugfixes event window

---

flood_adapt/object_model/hazard/event/event.py
tests/test_object_model/test_events.py

Reverts Deltares-research/FloodAdapt#534
It turns out the issue was unrelated, so these changes can be re-applied

Reapply changes from 524 

---

flood_adapt/dbs_controller.py
flood_adapt/object_model/hazard/event/event.py
flood_adapt/object_model/hazard/hazard.py
tests/test_object_model/test_events.py

536 time series column name format error

---

flood_adapt/integrator/sfincs_adapter.py
flood_adapt/object_model/hazard/hazard.py

The downloaded data had longitudes around 280 degrees and the SFINCS region around -80 degrees. So I simply subtracted 360 degrees from the downloaded data, if the minimum longitude is larger than 180 degrees. Seems like a dodgy fix but it worked.

Offshore model fix incl slicing error

---

docs/1_introduction/index.qmd

One small change to comment out the video and put a 'video coming soon' box so we can update the presentation video to not contain any copyrighted materials.

Commented out video until video is updated

---

flood_adapt/dbs_controller.py

merge with https://github.com/Deltares-research/FloodAdapt-GUI/pull/439

backend implementation for issue #431 in FloodAdapt-GUI

---

flood_adapt/database_builder/create_database.py

connects to https://github.com/Deltares/hydromt_fiat/pull/405

small correction based on change of spatial join read in hydromt fiat

---

flood_adapt/database_builder/create_database.py

small changes to be in line with hydromt-fiat changes in spatial joins model (now a dictionary and not an object)

small changes to be in line with hydromt-fiat changes in spatial joins

---

.commitlintrc.yml
docs/3_setup_guide/Delft_Fiat/hydromt_fiat_gui.qmd
docs/3_setup_guide/index.qmd
docs/4_user_guide/measures/hydraulic.qmd
docs/4_user_guide/output/index.qmd
docs/4_user_guide/projections/climate.qmd
docs/_make_pdf.qmd

Automate the creation of a PDF file from the online documentation

doc(misc): Automate pdf from docs

---

flood_adapt/adapter/fiat_adapter.py
flood_adapt/object_model/hazard/floodmap.py

This allows for the use of flood depth maps instead of water level maps, which means that the area method in FIAT can be used now with more accuracy.

feat(adapters): Use flood depth maps

---

flood_adapt/database_builder/create_database.py
flood_adapt/object_model/interface/config/gui.py
flood_adapt/object_model/interface/config/sfincs.py

The database builder now works with the new site config refactor.

fix(dbs-builder): Fixing database builder to work with site config refactor

---

flood_adapt/adapter/sfincs_adapter.py
flood_adapt/adapter/sfincs_offshore.py
flood_adapt/dbs_classes/database.py
tests/test_adapter/test_sfincs_adapter.py
tests/test_object_model/test_events/test_eventset.py
tests/test_object_model/test_scenarios.py

Some tests broke so still fixing that

fix(adapter): SfincsAdapter produces floodmap in correct units

---

flood_adapt/misc/config.py
flood_adapt/object_model/hazard/event/template_event.py
tests/conftest.py

fix(object-model): add validate_allowed_forcings to Settings class 

---

flood_adapt/object_model/hazard/interface/forcing.py

https://github.com/Deltares-research/FloodAdapt-GUI/pull/491

feat(object-model): add NONE as a forcingsource for use in the gui

---

flood_adapt/adapter/sfincs_adapter.py
flood_adapt/object_model/hazard/forcing/plotting.py
flood_adapt/object_model/hazard/forcing/rainfall.py
flood_adapt/object_model/hazard/forcing/wind.py

fix(object-model): standardize units attribute among all classes

---

flood_adapt/database_builder/create_database.py

A aggregation areas option has been added in the database builder config when additional aggregation areas should be added.

feat(dbs-builder): Allow for configuring new aggregation areas

---

flood_adapt/object_model/hazard/event/hurricane.py
flood_adapt/object_model/hazard/event/synthetic.py

https://github.com/Deltares-research/FloodAdapt-GUI/pull/499

fix(object-model): update allowed sources for events

---

flood_adapt/object_model/hazard/forcing/plotting.py

https://github.com/Deltares-research/FloodAdapt-GUI/pull/510

fix(object-model): update unit references in plotting

---

flood_adapt/adapter/sfincs_adapter.py
tests/test_adapter/test_sfincs_adapter.py

call correct hydromt sfincs function for RainfallCSV add tests for DischargeCSV, RainfallCSV and RainfallTrack sfincsadapter

fix(adapters): update hydromt-sfincs function calls in sfincsadapter

---

flood_adapt/database_builder/create_database.py

Before the "dis" forcing was looked for in the HydroMT SFINCS model, but that will not work if the forcing files (.dis) are not there, and only the location of the rivers (.src) is. 
So now a check is done for the actual .src file.

fix(dbs-builder): Corrected how the existense of rivers in the SFINCS model is checked

---

flood_adapt/api/measures.py

https://github.com/Deltares-research/FloodAdapt-GUI/pull/513

fix(api): add overwrite option to save_measure function

---

flood_adapt/adapter/fiat_adapter.py
flood_adapt/database_builder/create_database.py
flood_adapt/dbs_classes/database.py

- small correction in aggregation area id when region is used
- ensure no issues when geometries with no exposure csv rows are present
- corrected small bug with SVI existense check
- do not save the index in the output csv of the scenario
- correct error message when scenario run fails

fix(dbs-builder): Small bug fixes in database builder

---

flood_adapt/object_model/hazard/event/event_set.py

Event set frequency can be > 1

fix(object-model): Event set frequency can be > 1

---

flood_adapt/adapter/fiat_adapter.py

So far the damage types were hardcoded in the adapter to "Structure" and "Content". But these can sometimes be different or have different names in the FIAT model. Now, these values are extracted from the FIAT exposure.

fix(adapters): Added option to get damage types from fiat model

---

.github/workflows/sonar.yml
sonar-project.properties

ci(misc): add sonarcloud scanning

---

flood_adapt/database_builder/create_database.py

fix(dbs-builder): bug where footprints_path is a string when it is expected to be a Path

---

flood_adapt/object_model/hazard/event/hurricane.py

Dont recreate the spw file if it exists already -> reuse it

fix(object-model): change default for spw_file recreation to false

---

flood_adapt/database_builder/create_database.py
flood_adapt/dbs_classes/database.py
flood_adapt/object_model/hazard/forcing/plotting.py

https://github.com/Deltares-research/FloodAdapt-GUI/pull/518

fix(misc): prettify all string converted units

---

docs/_quarto.yml
flood_adapt/misc/config.py

fix(misc): Remove unit system from Settings class

---

flood_adapt/dbs_classes/database.py

fix(misc): improve directory cleanup with retry logic for locked files

---

.commitlintrc.yml
flood_adapt/adapter/sfincs_adapter.py
tests/test_api/test_scenarios.py

feat(adapter): add check for when converting scs or other rainfall to not error

---

distribution/build_database_builder_executable.py

copy_shapely function and update dependencies list

feat(distribution): update database builder executable creation script

---

flood_adapt/dbs_classes/database.py
flood_adapt/dbs_classes/dbs_event.py
flood_adapt/dbs_classes/dbs_template.py
tests/test_api/test_scenarios.py
tests/test_object_model/test_events/test_meteo.py
tests/test_object_model/test_events/test_tide_gauge.py

refactor(dbs-controller): update copy function in dbs template.

---

flood_adapt/adapter/sfincs_adapter.py

fix(adapter): updated _cleanup_simulation_folder() to check the config and delete the entire simulation if needed

---

flood_adapt/__init__.py
flood_adapt/dbs_classes/database.py
flood_adapt/dbs_classes/dbs_event.py
flood_adapt/dbs_classes/dbs_measure.py
flood_adapt/dbs_classes/dbs_template.py
flood_adapt/objects/events/events.py
flood_adapt/objects/forcing/timeseries.py
pixi.lock
pyproject.toml
tests/test_objects/test_forcing/test_timeseries.py

Fixes #https://github.com/Deltares-research/FloodAdapt-GUI/issues/504
Added logic for computing the area under the curve

feat(object-model): update synthetic rainfall to allow cumulative

---

.gitignore
docs/_quarto.yml
flood_adapt/config/site.py
flood_adapt/dbs_classes/dbs_static.py
flood_adapt/flood_adapt.py
flood_adapt/objects/__init__.py
flood_adapt/objects/benefits/benefits.py
flood_adapt/objects/events/event_set.py
flood_adapt/objects/events/events.py
flood_adapt/objects/events/historical.py
flood_adapt/objects/events/hurricane.py
flood_adapt/objects/events/synthetic.py
flood_adapt/objects/forcing/forcing.py
flood_adapt/objects/forcing/plotting.py
flood_adapt/objects/forcing/tide_gauge.py
flood_adapt/objects/forcing/time_frame.py
flood_adapt/objects/measures/measures.py
flood_adapt/objects/object_model.py
flood_adapt/objects/projections/projections.py
flood_adapt/objects/strategies/strategies.py
flood_adapt/workflows/benefit_runner.py
pixi.lock
pyproject.toml

Fixes #644 
Wen through the api and removed unused functions, renamed poorly named functions, checked all docstrings and type annotations etc.

refactor(api): cleanup api functions and signatures

---

pixi.lock
pyproject.toml
tests/data/create_test_static.py

Added tasks to run the update database scripts

feat(misc): added pixi tasks for updating the test database

---

LICENSE
pixi.lock
pyproject.toml

feat(distribution): update license from MIT to GNU GPL v3

---

flood_adapt/adapter/sfincs_adapter.py
flood_adapt/workflows/scenario_runner.py

Fixes bug where the check for hazard run was done on the simulation and not the flooding output

fix(adapter): Hazard has run check was performed on SFINCS simulation and not the output

---

pyproject.toml

Update dependency on hydromt fiat to v0.5.5

dep(adapter): Update to hydromt fiat v0.5.5

---

docs/index.qmd

Updates the home doc page with the intro video.

doc(misc): Added the intro video to the home page 

---

flood_adapt/adapter/sfincs_adapter.py
tests/test_adapter/test_fiat_adapter.py
tests/test_adapter/test_sfincs_adapter.py
tests/test_flood_adapt.py
tests/test_objects/test_events/test_eventset.py
tests/test_objects/test_events/test_offshore.py
tests/test_workflows/test_scenario_runner.py

instead of testing for no errors, we now test for actual values in the input files
Also improve tests for `add_measure()` by getting file from the config in the SfincsModel, and testing for the contents of that file
The generated waterlevels from SFINCS are not tested here. 
That is something we should probably do as well, but we are at least sure the inputs to SFINCS are as expected.

test(adapter): improve `add_forcing` tests to test for actual values

---

docs/examples/events/database_manipulation.ipynb
docs/examples/events/historical_event.ipynb
docs/examples/events/hurricane_event.ipynb
docs/examples/events/index.qmd
docs/examples/events/synthetic_event.ipynb

I reviewed the event example notebooks. Super comprehensive, which is nice. I added a bit of explanation here and there, so I created a PR for it.

doc(object-model): review and update event examples

---

flood_adapt/dbs_classes/database.py

Fixes #779 
removed if statement

fix(dbs-controller): cleanup of corrupted scneario output is always done at startup

---

.gitignore
docs/_quarto.yml
docs/clean_database.py
docs/clean_notebook_output.py
docs/examples/_sidebar.yml
docs/examples/events/event_modification.ipynb
docs/examples/events/historical_event.ipynb
docs/examples/index.qmd
docs/examples/scenarios/complex.ipynb
docs/examples/scenarios/simple.ipynb
docs/formatting_tips.qmd
pixi.lock
pyproject.toml
typos.toml

Added:
- pixi task `clean-example-output` (`clean_notebook_output.py`)
- pixi task `clean-example-database` (`clean_database.py`)

doc(misc): resolve sidebar issues for example notebooks 

---

flood_adapt/adapter/sfincs_adapter.py

fix(adapter): Check save_simulation config before deleting SFINCS folders

---

flood_adapt/adapter/sfincs_offshore.py

fix(adapter): Do not copy the template offshore SFINCS model and overwrite it anymore, to avoid file open errors

---

flood_adapt/adapter/sfincs_adapter.py

fix(adapter): Opens templates and save in new sim, instead of copying and overwriting the overlands SFINCS model

---

flood_adapt/adapter/sfincs_adapter.py
tests/test_adapter/test_sfincs_adapter.py

test(adapter):  Add unit tests for return period flood maps calculation

---

flood_adapt/dbs_classes/dbs_benefit.py
flood_adapt/dbs_classes/dbs_event.py
flood_adapt/dbs_classes/dbs_measure.py
flood_adapt/dbs_classes/dbs_projection.py
flood_adapt/dbs_classes/dbs_scenario.py
flood_adapt/dbs_classes/dbs_strategy.py
flood_adapt/dbs_classes/dbs_template.py

Fixes [#604](https://github.com/Deltares-research/FloodAdapt-GUI/issues/604)

feat(dbs-controller): Add `_higher_lvl_object` attribute to dbs classes for improved error msgs

---

flood_adapt/database_builder/database_builder.py

refactor(dbs-builder): Small script corrections

---

flood_adapt/database_builder/database_builder.py

CRS check and reprojection in case FIAT crs is different than the SFINCS one. Additionally, delete the large subgrid folder from the sinfcs template so we dont copy it all the time.

fix(dbs-builder): Made sure crs of dem and fiat are the same

---

flood_adapt/adapter/fiat_adapter.py
flood_adapt/config/gui.py
flood_adapt/flood_adapt.py
pyproject.toml

Connects to https://github.com/Deltares-research/FloodAdapt-GUI/issues/625
A new `MetricLayer` class has been created which allows for filters to be applied in order to find the metrics that fall within that type of layer. So you can define a building count layer, a people count or road length based on strings that are in specific attributes.

feat(object-model): Allow for choosing different spatial infometrics to show
